export enum Note {
    ANGULAR = "Angular",
    NGRX = "NgRx",
    RXJS = "RxJs",
    JAVASCRIPT = "JavaScript",
    TYPESCRIPT = "TypeScript",
    HTML = "HTML",
    CSS = "CSS",
    AZURE = "AZURE",
    ANGULAR_MICROFRONTEND = "AngularMicroFrontend",
    PRACTICE_SET = "PracticeSet",
    ANGULAR_UNIT_TEST = "AngularUnitTest",
    ANGULAR_VERSION_FEATURES = "AngularVersionFeatures",
    ANGULAR_RELATED_FRONTEND = "AngularRelatedFrontend",
}