export const AngularRelatedFrontend = () => {
    return [
        {
            "name": "<p><strong>Frountend related questions</strong></p>",
            "sectionId": 73,
            "noteType": "AngularRelatedFrontend",
            "topics": [],
            "subSections": [
                {
                    "name": "<p><strong>Tokens</strong></p>",
                    "sectionId": 73,
                    "subSectionId": 22,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p>What are authorization tokens in angular?</p>",
                            "sectionId": 73,
                            "subSectionId": 22,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 365,
                            "description": "<p><strong>Authorization Tokens: </strong></p><p>Authorization tokens are <strong>pieces of data (usually a string)</strong> issued by the server that prove a user is <strong>authenticated</strong> and has permission to access certain resources.</p></br><p><strong>Common Types:</strong></p><ol><li><strong>JWT (JSON Web Token)</strong> – Encodes user info and expiry time.</li><li><strong>OAuth Tokens</strong> – Access tokens issued by OAuth providers.</li><li><strong>Custom tokens</strong> – Sometimes generated by your backend.</li></ol></br>"
                        },
                        {
                            "text": "<p>Do you have any idea about bearer token and JWT token?</p>",
                            "sectionId": 73,
                            "subSectionId": 22,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 366,
                            "description": "<p>A <strong>Bearer Token</strong> is used for <strong>authorization</strong>, while a <strong>JWT token</strong> can be used for both <strong>authorization</strong> and carrying <strong>user data/claims</strong>.</p>"
                        }
                    ]
                },
                {
                    "name": "<p><strong>Restful API and HTTP</strong></p>",
                    "sectionId": 73,
                    "subSectionId": 23,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p>What is a Restful API?</p>",
                            "sectionId": 73,
                            "subSectionId": 23,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 367,
                            "description": "<p>A <strong>REST API</strong> (Representational State Transfer Application Programming Interface) is a way for two systems (such as a <strong>frontend app</strong> and a <strong>backend server</strong>) to communicate over the Internet using standard <strong>HTTP methods</strong>.</p></br><p><strong>Common HTTP methods:</strong></p><ul><li><strong>GET</strong> → Retrieve data</li><li><strong>POST</strong> → Create new data</li><li><strong>PUT / PATCH</strong> → Update existing data</li><li><strong>DELETE</strong> → Remove data</li></ul></br>"
                        },
                        {
                            "text": "<p>What are HTTP Status Codes?</p>",
                            "sectionId": 73,
                            "subSectionId": 23,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 368,
                            "description": "<p><strong>HTTP Status Codes</strong> are <strong>three-digit numbers</strong> returned by a <strong>server</strong> in response to a <strong>client’s request.</strong></p></br><p><strong>Most Common HTTP Status Codes:</strong></p><table style=\"border: 1px solid #000;\"><tbody><tr><td data-row=\"2\"><strong>200 OK</strong></td><td data-row=\"2\">Success</td><td data-row=\"2\">Request completed successfully</td></tr><tr><td data-row=\"3\"><strong>201 Created</strong></td><td data-row=\"3\">Resource Created</td><td data-row=\"3\">New record created (e.g., signup, post creation)</td></tr><tr><td data-row=\"4\"><strong>204 No Content</strong></td><td data-row=\"4\">Success without data</td><td data-row=\"4\">Request successful, no body returned</td></tr><tr><td data-row=\"5\"><strong>301 Moved Permanently</strong></td><td data-row=\"5\">Redirect</td><td data-row=\"5\">URL changed permanently</td></tr><tr><td data-row=\"6\"><strong>400 Bad Request</strong></td><td data-row=\"6\">Invalid Input</td><td data-row=\"6\">Request format or data is wrong</td></tr><tr><td data-row=\"7\"><strong>401 Unauthorized</strong></td><td data-row=\"7\">Authentication Failed</td><td data-row=\"7\">Token missing/invalid</td></tr><tr><td data-row=\"8\"><strong>403 Forbidden</strong></td><td data-row=\"8\">Access Denied</td><td data-row=\"8\">You’re authenticated but not allowed</td></tr><tr><td data-row=\"9\"><strong>404 Not Found</strong></td><td data-row=\"9\">Resource Missing</td><td data-row=\"9\">Endpoint or data not found</td></tr><tr><td data-row=\"10\"><strong>409 Conflict</strong></td><td data-row=\"10\">Duplicate data</td><td data-row=\"10\">Same record already exists</td></tr><tr><td data-row=\"11\"><strong>500 Internal Server Error</strong></td><td data-row=\"11\">Server crashed</td><td data-row=\"11\">Code exception or backend failure</td></tr><tr><td data-row=\"12\"><strong>502 Bad Gateway</strong></td><td data-row=\"12\">Gateway problem</td><td data-row=\"12\">Reverse proxy/server issue</td></tr><tr><td data-row=\"13\"><strong>503 Service Unavailable</strong></td><td data-row=\"13\">Server Down</td><td data-row=\"13\">Maintenance or overload</td></tr><tr><td data-row=\"14\"><strong>504 Gateway Timeout</strong></td><td data-row=\"14\">Timeout</td><td data-row=\"14\">Server didn’t respond in time</td></tr></tbody></table></br>"
                        },
                        {
                            "text": "<p>What is the difference between 4xx and 5xx?</p>",
                            "sectionId": 73,
                            "subSectionId": 23,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 369,
                            "description": "<p>4xx = client-side issue (your request), 5xx = server-side issue.</p>"
                        },
                        {
                            "text": "<p>What happens when you get 401 or 403?</p>",
                            "sectionId": 73,
                            "subSectionId": 23,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 370,
                            "description": "<p>401 = not logged in or token invalid.</p></br><p>403 = logged in but access denied.</p>"
                        }
                    ]
                },
                {
                    "name": "<p><strong>Socket</strong></p>",
                    "sectionId": 73,
                    "subSectionId": 24,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p>What is Socket?</p>",
                            "sectionId": 73,
                            "subSectionId": 24,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 372,
                            "description": ""
                        }
                    ]
                },
                {
                    "name": "<p><strong>SDLC (Software Development Life Cycle) and project methodology</strong></p>",
                    "sectionId": 73,
                    "subSectionId": 25,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p>Which model or process is followed in your project?</p>",
                            "sectionId": 73,
                            "subSectionId": 25,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 373,
                            "description": "<p>In our project, we follow the <strong>Agile model</strong>, specifically the <strong>Scrum process</strong>.</p><p>Our development is divided into <strong>sprints</strong>, usually of <strong>two weeks</strong>.</p></br><p>At the beginning of each sprint, we conduct a <strong>Sprint Planning Meeting</strong> to discuss and finalize the features or tasks to be developed.</p></br><p>Every day, we have a <strong>daily stand-up meeting</strong> where each team member shares their progress, challenges, and plans for the day.</p></br><p>Once the sprint ends, we conduct a <strong>Sprint Review</strong> to demonstrate the completed work to stakeholders and get feedback.</p><p>Then, we have a <strong>Sprint Retrospective</strong> to identify what went well, what didn’t, and how we can improve in the next sprint.</p></br><p>This process helps us deliver features incrementally, respond quickly to changes in requirements, and maintain good collaboration between developers, testers, and product owners.</p>"
                        },
                        {
                            "text": "<p>What is Agile Model?</p>",
                            "sectionId": 73,
                            "subSectionId": 25,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 374,
                            "description": "<p>The <strong>Agile Model</strong> is a <strong>software development approach</strong> where the project is divided into <strong>small parts called sprints or iterations</strong>, and each sprint delivers a <strong>working piece of the product</strong>.</p><p>It focuses on <strong>continuous feedback, flexibility, and fast delivery</strong> instead of completing everything at once like the traditional Waterfall model.</p>"
                        },
                        {
                            "text": "<p>What is CI/CD Model?</p>",
                            "sectionId": 73,
                            "subSectionId": 25,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 375,
                            "description": "<p><strong>CI/CD</strong> stands for <strong>Continuous Integration</strong> and <strong>Continuous Delivery (or Deployment)</strong>.</p><p>It is a <strong>DevOps practice</strong> that automates the process of building, testing, and deploying code to ensure faster and more reliable software delivery.</p>"
                        },
                        {
                            "text": "<p>What is DevOps?</p>",
                            "sectionId": 73,
                            "subSectionId": 25,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 376,
                            "description": "<p><strong>DevOps</strong> is a combination of <strong>Development (Dev)</strong> and <strong>Operations (Ops)</strong>.</p><p>It is a <strong>culture and set of practices</strong> that brings <strong>developers and operations teams together</strong> to build, test, and release software <strong>faster, more reliably, and with better collaboration</strong>.</p>"
                        },
                        {
                            "text": "<p>What is Solid Principle?</p>",
                            "sectionId": 73,
                            "subSectionId": 25,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 377,
                            "description": "<p>The <strong>SOLID Principles</strong> are <strong>five key design principles</strong> in <strong>object-oriented programming (OOP)</strong> that help you write <strong>clean, maintainable, and scalable code</strong>.</p></br><p>They are especially useful in frameworks like Angular, React, or backend systems (Java, Node.js, etc.) when you design services, classes, or components.</p></br><table style=\"border: 1px solid #000;\"><tbody><tr><td data-row=\"1\">Letter Principle Purpose</td></tr><tr><td data-row=\"2\"><strong>S</strong></td><td data-row=\"2\"><strong>Single Responsibility Principle (SRP)</strong></td><td data-row=\"2\">A class should have <strong>only one reason to change</strong> — i.e., one responsibility.</td></tr><tr><td data-row=\"3\"><strong>O</strong></td><td data-row=\"3\"><strong>Open/Closed Principle (OCP)</strong></td><td data-row=\"3\">Classes should be <strong>open for extension</strong>, but <strong>closed for modification</strong>.</td></tr><tr><td data-row=\"4\"><strong>L</strong></td><td data-row=\"4\"><strong>Liskov Substitution Principle (LSP)</strong></td><td data-row=\"4\">Subclasses should be <strong>replaceable</strong> with their base classes <strong>without breaking functionality</strong>.</td></tr><tr><td data-row=\"5\"><strong>I</strong></td><td data-row=\"5\"><strong>Interface Segregation Principle (ISP)</strong></td><td data-row=\"5\">Don’t force a class to implement <strong>interfaces it doesn’t use</strong>.</td></tr><tr><td data-row=\"6\"><strong>D</strong></td><td data-row=\"6\"><strong>Dependency Inversion Principle (DIP)</strong></td><td data-row=\"6\">Depend on <strong>abstractions</strong>, not <strong>concrete implementations</strong>.</td></tr></tbody></table></br>"
                        }
                    ]
                },
                {
                    "name": "<p><strong>CORS (Cross-Origin Resource Sharing)</strong></p>",
                    "sectionId": 73,
                    "subSectionId": 26,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">What is CORS (Cross-Origin Resource Sharing)</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">, and why do we face </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">CORS errors</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\"> in Angular applications?</span></p>",
                            "sectionId": 73,
                            "subSectionId": 26,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 378,
                            "description": ""
                        }
                    ]
                }
            ]
        },
        {
            "name": "<p><strong>SSR</strong></p>",
            "sectionId": 75,
            "noteType": "AngularRelatedFrontend",
            "topics": [
                {
                    "text": "<p><strong style=\"color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);\">What is SSR (Server-Side Rendering)</strong><span style=\"color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);\">, and why is it used in Angular?</span></p>",
                    "sectionId": 75,
                    "subSectionId": -1,
                    "noteType": "AngularRelatedFrontend",
                    "topicId": 382,
                    "description": ""
                },
                {
                    "text": "<p><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">What are the </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">benefits of SSR</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\"> in terms of </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">SEO</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\"> and </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">performance</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">?</span></p>",
                    "sectionId": 75,
                    "subSectionId": -1,
                    "noteType": "AngularRelatedFrontend",
                    "topicId": 383,
                    "description": ""
                }
            ],
            "subSections": []
        },
        {
            "name": "<p><strong>Caching, Webpack and Auth</strong></p>",
            "sectionId": 74,
            "noteType": "AngularRelatedFrontend",
            "topics": [],
            "subSections": [
                {
                    "name": "<p><strong>Caching</strong></p>",
                    "sectionId": 74,
                    "subSectionId": 27,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">What is </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">caching</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">, and how do you implement </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">caching</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\"> in Angular?</span></p>",
                            "sectionId": 74,
                            "subSectionId": 27,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 379,
                            "description": ""
                        }
                    ]
                },
                {
                    "name": "<p><strong>Webpack</strong></p>",
                    "sectionId": 74,
                    "subSectionId": 28,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">What is Webpack</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">, and how is it used in </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">Angular</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">?</span></p>",
                            "sectionId": 74,
                            "subSectionId": 28,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 380,
                            "description": "<p><strong>Webpack</strong> is a <strong>module bundler</strong> — it takes all the files and dependencies in your Angular project (like TypeScript, HTML, SCSS, images, etc.) and bundles them into optimized JavaScript files that the browser can understand and load efficiently.</p></br><p><strong>How Webpack is used in Angular:</strong></p><p>Angular uses Webpack <strong>under the hood</strong> through the <strong>Angular CLI</strong>.</p><p>You don’t manually configure Webpack — it’s already integrated and managed internally by Angular CLI (<code>@angular/cli</code>).</p><p>When you run Angular CLI commands, Webpack is working behind the scenes:</p><table style=\"border: 1px solid #000;\"><tbody><tr><td data-row=\"1\"></td></tr><tr><td data-row=\"2\"><code>ng serve</code></td><td data-row=\"2\">Starts a <strong>Webpack Dev Server</strong> for live reloading during development.</td></tr><tr><td data-row=\"3\"><code>ng build</code></td><td data-row=\"3\">Uses Webpack to bundle and optimize code (tree-shaking, minification, lazy loading).</td></tr><tr><td data-row=\"4\"><code>ng test</code></td><td data-row=\"4\">Webpack bundles test files before running them.</td></tr></tbody></table></br>"
                        }
                    ]
                },
                {
                    "name": "<p><strong>Auth</strong></p>",
                    "sectionId": 74,
                    "subSectionId": 29,
                    "noteType": "AngularRelatedFrontend",
                    "topics": [
                        {
                            "text": "<p><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">Can you explain </span><strong style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">Auth</strong><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">?</span></p>",
                            "sectionId": 74,
                            "subSectionId": 29,
                            "noteType": "AngularRelatedFrontend",
                            "topicId": 381,
                            "description": ""
                        }
                    ]
                }
            ]
        }
    ];
}